### ISSUE TITLE
SpaceX Dashboard Challenge

### ISSUE THREAD

**Issue by mayank-khare** [mayank-khare/SpaceX-Dashboard-React#1]
https://public.3.basecamp.com/p/UGEyqrnc11MEXx8ndGmJcA49

**Comment by mayank-khare** [comment]
App deployed at - https://dashboard-mayank.herokuapp.com/

**Comment by mayank-khare** [comment]
The application is ready for code review.

**Comment by vinay0x** [comment]
Please pick a timeslot for the next phase of your interview process: http://calendly.com/vinaychandranvs/vinay-v-1
